// @sddp/activities/projects - Stores

// Projects Store
export {
  projectsStore,
  setProjects,
  setProjectsLoading,
  setProjectsError,
  addProject,
  updateProjectInList,
  removeProject,
  setCurrentProject,
  setCurrentProjectLoading,
  setCurrentProjectError,
  clearCurrentProject,
  updateCurrentProject,
  toggleProjectExpanded,
  setProjectExpanded,
  setSelectedNodePath,
  expandAllProjects,
  collapseAllProjects,
  setSearchQuery,
  clearSearchQuery,
  getProjectsState,
  getProjects,
  getFilteredProjects,
  getCurrentProject,
  getExpandedProjects,
  getSelectedNodePath,
  isProjectExpanded,
  getProjectBadgesFromStore,
  loadProjectDetail,
  subscribeProjects,
  resetProjectsStore,
  setPendingEntityId,
  consumePendingEntityId,
} from './projects.store';

// Timeline Store
export {
  timelineStore,
  setTimelineEvents,
  setTimelineLoading,
  setTimelineError,
  addTimelineEvent,
  removeTimelineEvent,
  clearTimelineEvents,
  setTimelineFilter,
  setFilterPeriod,
  setFilterEventTypes,
  clearTimelineFilter,
  setTimelineExpanded,
  toggleTimelineExpanded,
  getTimelineState,
  getTimelineEvents,
  getFilteredEvents,
  getTimelineFilter,
  isTimelineExpanded,
  getProjectEvents,
  subscribeTimeline,
  resetTimelineStore,
} from './timeline.store';

// Re-export types
export type { ProjectsState, TimelineState } from '../types';
